// Generated by CoffeeScript 1.4.0
(function() {

  $.specificity = function(selector) {
    var m, matches, p, result, sel, selectors, specificity, tmp, _i, _j, _len, _len1;
    specificity = [0, 0, 0, 0, 0];
    tmp = 0;
    selectors = selector.split(/\s*,\s*/);
    for (_i = 0, _len = selectors.length; _i < _len; _i++) {
      sel = selectors[_i];
      matches = sel.match(/#/g);
      if (matches) {
        specificity[1] += matches.length;
      }
      matches = sel.match(/\./g);
      if (matches) {
        specificity[2] += matches.length;
      }
      matches = sel.match(/\[.+\]/g);
      if (matches) {
        specificity[2] += matches.length;
      }
      matches = sel.match(/:(?:first-letter|first-line|before|after|:selection)/g);
      if (matches) {
        tmp = matches.length;
        specificity[3] += tmp;
      }
      matches = sel.match(/:/g);
      if (matches) {
        specificity[2] += matches.length - tmp;
      }
      tmp = 0;
      matches = sel.match(/[+>~]/g);
      if (matches) {
        specificity[4] += matches.length;
      }
      sel = sel.replace(/\(.*?\)/g, "").replace(/\[.*?\]/g, "").replace(/[.#:][^ +>~]*/ig, "");
      matches = sel.match(/[^ +>~]+/g);
      if (matches) {
        specificity[3] += matches.length;
      }
    }
    m = 10000;
    result = 0;
    for (_j = 0, _len1 = specificity.length; _j < _len1; _j++) {
      p = specificity[_j];
      result += p * m;
      m /= 10;
    }
    return result;
  };

}).call(this);
